# This Makefile is for the NicToolServer extension to perl.
#
# It was generated automatically by MakeMaker version
# 7.76 (Revision: 77600) from the contents of
# Makefile.PL. Don't edit this file, edit Makefile.PL instead.
#
#       ANY CHANGES MADE HERE WILL BE LOST!
#
#   MakeMaker ARGV: ()
#

#   MakeMaker Parameters:

#     ABSTRACT => q[NicTool API reference server]
#     AUTHOR => [q[Matt Simerson <msimerson@cpan.org>, Damon Edwards, Abe Shelton, Greg Schueler]]
#     BUILD_REQUIRES => {  }
#     CONFIGURE_REQUIRES => { ExtUtils::MakeMaker=>q[0] }
#     DISTNAME => q[NicToolServer]
#     EXE_FILES => []
#     LICENSE => q[open_source]
#     NAME => q[NicToolServer]
#     PREREQ_PM => { Apache::DBI=>q[0], BIND::Conf_Parser=>q[0], CGI=>q[4.21], Crypt::KeyDerivation=>q[0], Crypt::Mac::HMAC=>q[0], CryptX=>q[0.021], Cwd=>q[0], DBD::MariaDB=>q[0], DBI=>q[1.20], DBIx::Simple=>q[0], Data::Dumper=>q[0], English=>q[0], Exporter=>q[0], File::Copy=>q[0], File::Path=>q[0], HTML::Parser=>q[0], IO::File=>q[0], JSON=>q[0], LWP::UserAgent=>q[0], MIME::Base32=>q[0], MIME::Base64=>q[0], Net::DNS::ZoneFile=>q[0], Net::IP=>q[0], Params::Validate=>q[0.8], RPC::XML=>q[0], RPC::XML::Parser=>q[0], SOAP::Lite=>q[0.51], Scalar::Util=>q[0], Test=>q[0], Test::More=>q[0], Test::Output=>q[0], Time::HiRes=>q[1.9], Time::Local=>q[0], Time::TAI64=>q[2], XML::Parser=>q[0], constant=>q[0], lib=>q[0], parent=>q[0.2], strict=>q[0], vars=>q[0], warnings=>q[0] }
#     TEST_REQUIRES => { Exporter=>q[0], Test=>q[0], Test::More=>q[0], Test::Output=>q[0] }
#     VERSION => q[2.35]
#     test => { TESTS=>q[t/*.t] }

# --- MakeMaker post_initialize section:


# --- MakeMaker const_config section:

# These definitions are from config.sh (via /opt/local/lib/perl5/5.34/darwin-thread-multi-2level/Config.pm).
# They may have been overridden via Makefile.PL or on the command line.
AR = ar
CC = /usr/bin/cc
CCCDLFLAGS =  
CCDLFLAGS =  
CPPRUN = /usr/bin/cc  -I/opt/local/include  -E
DLEXT = bundle
DLSRC = dl_dlopen.xs
EXE_EXT = 
FULL_AR = /usr/bin/ar
LD = /usr/bin/cc
LDDLFLAGS =   -bundle -undefined dynamic_lookup -L/opt/local/lib -Wl,-headerpad_max_install_names   -fstack-protector-strong
LDFLAGS =   -L/opt/local/lib -Wl,-headerpad_max_install_names   -fstack-protector-strong
LIBC = 
LIB_EXT = .a
OBJ_EXT = .o
OSNAME = darwin
OSVERS = 25.0.0
RANLIB = ranlib
SITELIBEXP = /opt/local/lib/perl5/site_perl/5.34
SITEARCHEXP = /opt/local/lib/perl5/site_perl/5.34/darwin-thread-multi-2level
SO = dylib
VENDORARCHEXP = /opt/local/lib/perl5/vendor_perl/5.34/darwin-thread-multi-2level
VENDORLIBEXP = /opt/local/lib/perl5/vendor_perl/5.34


# --- MakeMaker constants section:
AR_STATIC_ARGS = cr
DIRFILESEP = /
DFSEP = $(DIRFILESEP)
NAME = NicToolServer
NAME_SYM = NicToolServer
VERSION = 2.35
VERSION_MACRO = VERSION
VERSION_SYM = 2_35
DEFINE_VERSION = -D$(VERSION_MACRO)=\"$(VERSION)\"
XS_VERSION = 2.35
XS_VERSION_MACRO = XS_VERSION
XS_DEFINE_VERSION = -D$(XS_VERSION_MACRO)=\"$(XS_VERSION)\"
INST_ARCHLIB = blib/arch
INST_SCRIPT = blib/script
INST_BIN = blib/bin
INST_LIB = blib/lib
INST_MAN1DIR = blib/man1
INST_MAN3DIR = blib/man3
MAN1EXT = 1pm
MAN3EXT = 3pm
MAN1SECTION = 1
MAN3SECTION = 3
INSTALLDIRS = site
DESTDIR = 
PREFIX = $(SITEPREFIX)
PERLPREFIX = /opt/local
SITEPREFIX = /opt/local
VENDORPREFIX = /opt/local
INSTALLPRIVLIB = /opt/local/lib/perl5/5.34
DESTINSTALLPRIVLIB = $(DESTDIR)$(INSTALLPRIVLIB)
INSTALLSITELIB = /opt/local/lib/perl5/site_perl/5.34
DESTINSTALLSITELIB = $(DESTDIR)$(INSTALLSITELIB)
INSTALLVENDORLIB = /opt/local/lib/perl5/vendor_perl/5.34
DESTINSTALLVENDORLIB = $(DESTDIR)$(INSTALLVENDORLIB)
INSTALLARCHLIB = /opt/local/lib/perl5/5.34/darwin-thread-multi-2level
DESTINSTALLARCHLIB = $(DESTDIR)$(INSTALLARCHLIB)
INSTALLSITEARCH = /opt/local/lib/perl5/site_perl/5.34/darwin-thread-multi-2level
DESTINSTALLSITEARCH = $(DESTDIR)$(INSTALLSITEARCH)
INSTALLVENDORARCH = /opt/local/lib/perl5/vendor_perl/5.34/darwin-thread-multi-2level
DESTINSTALLVENDORARCH = $(DESTDIR)$(INSTALLVENDORARCH)
INSTALLBIN = /opt/local/bin
DESTINSTALLBIN = $(DESTDIR)$(INSTALLBIN)
INSTALLSITEBIN = /opt/local/libexec/perl5.34/sitebin
DESTINSTALLSITEBIN = $(DESTDIR)$(INSTALLSITEBIN)
INSTALLVENDORBIN = /opt/local/libexec/perl5.34
DESTINSTALLVENDORBIN = $(DESTDIR)$(INSTALLVENDORBIN)
INSTALLSCRIPT = /opt/local/bin
DESTINSTALLSCRIPT = $(DESTDIR)$(INSTALLSCRIPT)
INSTALLSITESCRIPT = /opt/local/libexec/perl5.34/sitebin
DESTINSTALLSITESCRIPT = $(DESTDIR)$(INSTALLSITESCRIPT)
INSTALLVENDORSCRIPT = /opt/local/libexec/perl5.34
DESTINSTALLVENDORSCRIPT = $(DESTDIR)$(INSTALLVENDORSCRIPT)
INSTALLMAN1DIR = /opt/local/share/man/man1
DESTINSTALLMAN1DIR = $(DESTDIR)$(INSTALLMAN1DIR)
INSTALLSITEMAN1DIR = /opt/local/share/perl5.34/siteman/man1
DESTINSTALLSITEMAN1DIR = $(DESTDIR)$(INSTALLSITEMAN1DIR)
INSTALLVENDORMAN1DIR = /opt/local/share/perl5.34/man/man1
DESTINSTALLVENDORMAN1DIR = $(DESTDIR)$(INSTALLVENDORMAN1DIR)
INSTALLMAN3DIR = /opt/local/share/man/man3
DESTINSTALLMAN3DIR = $(DESTDIR)$(INSTALLMAN3DIR)
INSTALLSITEMAN3DIR = /opt/local/share/perl5.34/siteman/man3
DESTINSTALLSITEMAN3DIR = $(DESTDIR)$(INSTALLSITEMAN3DIR)
INSTALLVENDORMAN3DIR = /opt/local/share/perl5.34/man/man3
DESTINSTALLVENDORMAN3DIR = $(DESTDIR)$(INSTALLVENDORMAN3DIR)
PERL_LIB = /opt/local/lib/perl5/5.34
PERL_ARCHLIB = /opt/local/lib/perl5/5.34/darwin-thread-multi-2level
LIBPERL_A = libperl.a
FIRST_MAKEFILE = Makefile
MAKEFILE_OLD = Makefile.old
MAKE_APERL_FILE = Makefile.aperl
PERLMAINCC = $(CC)
PERL_INC = /opt/local/lib/perl5/5.34/darwin-thread-multi-2level/CORE
PERL = "/opt/local/bin/perl5.34"
FULLPERL = "/opt/local/bin/perl5.34"
ABSPERL = $(PERL)
PERLRUN = $(PERL)
FULLPERLRUN = $(FULLPERL)
ABSPERLRUN = $(ABSPERL)
PERLRUNINST = $(PERLRUN) "-I$(INST_ARCHLIB)" "-I$(INST_LIB)"
FULLPERLRUNINST = $(FULLPERLRUN) "-I$(INST_ARCHLIB)" "-I$(INST_LIB)"
ABSPERLRUNINST = $(ABSPERLRUN) "-I$(INST_ARCHLIB)" "-I$(INST_LIB)"
PERL_CORE = 0
PERM_DIR = 755
PERM_RW = 644
PERM_RWX = 755

MAKEMAKER   = /opt/local/lib/perl5/vendor_perl/5.34/ExtUtils/MakeMaker.pm
MM_VERSION  = 7.76
MM_REVISION = 77600

# FULLEXT = Pathname for extension directory (eg Foo/Bar/Oracle).
# BASEEXT = Basename part of FULLEXT. May be just equal FULLEXT. (eg Oracle)
# PARENT_NAME = NAME without BASEEXT and no trailing :: (eg Foo::Bar)
# DLBASE  = Basename part of dynamic library. May be just equal BASEEXT.
MAKE = make
FULLEXT = NicToolServer
BASEEXT = NicToolServer
PARENT_NAME = 
DLBASE = $(BASEEXT)
VERSION_FROM = 
OBJECT = 
LDFROM = $(OBJECT)
LINKTYPE = dynamic
BOOTDEP = 

# Handy lists of source code files:
XS_FILES = 
C_FILES  = 
O_FILES  = 
H_FILES  = 
MAN1PODS = 
MAN3PODS = lib/NicToolServer.pm \
	lib/NicToolServer/Client.pm \
	lib/NicToolServer/Client/SOAP.pm \
	lib/NicToolServer/Export.pm \
	lib/NicToolServer/Export/BIND.pm \
	lib/NicToolServer/Export/BIND/nsupdate.pm \
	lib/NicToolServer/Export/Base.pm \
	lib/NicToolServer/Export/DynECT.pm \
	lib/NicToolServer/Export/Knot.pm \
	lib/NicToolServer/Export/MaraDNS.pm \
	lib/NicToolServer/Export/NSD.pm \
	lib/NicToolServer/Export/PowerDNS.pm \
	lib/NicToolServer/Export/tinydns.pm \
	lib/NicToolServer/Group.pm \
	lib/NicToolServer/Group/Sanity.pm \
	lib/NicToolServer/Import/BIND.pm \
	lib/NicToolServer/Import/Base.pm \
	lib/NicToolServer/Import/tinydns.pm \
	lib/NicToolServer/Nameserver.pm \
	lib/NicToolServer/Nameserver/Sanity.pm \
	lib/NicToolServer/Permission.pm \
	lib/NicToolServer/Response.pm \
	lib/NicToolServer/SOAP.pm \
	lib/NicToolServer/Session.pm \
	lib/NicToolServer/User.pm \
	lib/NicToolServer/User/Sanity.pm \
	lib/NicToolServer/Zone.pm \
	lib/NicToolServer/Zone/Record.pm \
	lib/NicToolServer/Zone/Record/Sanity.pm \
	lib/NicToolServer/Zone/Sanity.pm

# Where to build things
INST_LIBDIR      = $(INST_LIB)
INST_ARCHLIBDIR  = $(INST_ARCHLIB)

INST_AUTODIR     = $(INST_LIB)/auto/$(FULLEXT)
INST_ARCHAUTODIR = $(INST_ARCHLIB)/auto/$(FULLEXT)

INST_STATIC      = 
INST_DYNAMIC     = 
INST_BOOT        = 

# Extra linker info
EXPORT_LIST        = 
PERL_ARCHIVE       = 
PERL_ARCHIVE_AFTER = 


TO_INST_PM = lib/NicToolServer.pm \
	lib/NicToolServer/Client.pm \
	lib/NicToolServer/Client/SOAP.pm \
	lib/NicToolServer/Export.pm \
	lib/NicToolServer/Export/BIND.pm \
	lib/NicToolServer/Export/BIND/nsupdate.pm \
	lib/NicToolServer/Export/Base.pm \
	lib/NicToolServer/Export/DynECT.pm \
	lib/NicToolServer/Export/Knot.pm \
	lib/NicToolServer/Export/MaraDNS.pm \
	lib/NicToolServer/Export/NSD.pm \
	lib/NicToolServer/Export/PowerDNS.pm \
	lib/NicToolServer/Export/tinydns.pm \
	lib/NicToolServer/Group.pm \
	lib/NicToolServer/Group/Sanity.pm \
	lib/NicToolServer/Import/BIND.pm \
	lib/NicToolServer/Import/Base.pm \
	lib/NicToolServer/Import/tinydns.pm \
	lib/NicToolServer/Nameserver.pm \
	lib/NicToolServer/Nameserver/Sanity.pm \
	lib/NicToolServer/Permission.pm \
	lib/NicToolServer/Response.pm \
	lib/NicToolServer/SOAP.pm \
	lib/NicToolServer/Session.pm \
	lib/NicToolServer/User.pm \
	lib/NicToolServer/User/Sanity.pm \
	lib/NicToolServer/Zone.pm \
	lib/NicToolServer/Zone/Record.pm \
	lib/NicToolServer/Zone/Record/Sanity.pm \
	lib/NicToolServer/Zone/Sanity.pm \
	lib/nictoolserver.conf \
	lib/nictoolserver.conf.dist
PERL_ARCHLIBDEP = /opt/local/lib/perl5/5.34/darwin-thread-multi-2level
PERL_INCDEP = /opt/local/lib/perl5/5.34/darwin-thread-multi-2level/CORE


# Dependencies info
PERL_ARCHIVEDEP    = 

# Where is the Config information that we are using/depend on
CONFIGDEP = $(PERL_ARCHLIBDEP)$(DFSEP)Config.pm $(PERL_INCDEP)$(DFSEP)config.h


# --- MakeMaker platform_constants section:
MM_Unix_VERSION = 7.76
PERL_MALLOC_DEF = -DPERL_EXTMALLOC_DEF -Dmalloc=Perl_malloc -Dfree=Perl_mfree -Drealloc=Perl_realloc -Dcalloc=Perl_calloc


# --- MakeMaker tool_autosplit section:
# Usage: $(AUTOSPLITFILE) FileToSplit AutoDirToSplitInto
AUTOSPLITFILE = $(ABSPERLRUN)  -e 'use AutoSplit;  autosplit($$$$ARGV[0], $$$$ARGV[1], 0, 1, 1)' --



# --- MakeMaker tool_xsubpp section:


# --- MakeMaker tools_other section:
SHELL = /bin/sh
CHMOD = chmod
CP = cp
MV = mv
NOOP = $(TRUE)
NOECHO = @
RM_F = rm -f
RM_RF = rm -rf
TEST_F = test -f
TOUCH = touch
UMASK_NULL = umask 0
DEV_NULL = > /dev/null 2>&1
MKPATH = $(ABSPERLRUN) -MExtUtils::Command -e 'mkpath' --
EQUALIZE_TIMESTAMP = $(ABSPERLRUN) -MExtUtils::Command -e 'eqtime' --
FALSE = false
TRUE = true
ECHO = echo
ECHO_N = echo -n
UNINST = 0
VERBINST = 0
MOD_INSTALL = $(ABSPERLRUN) -MExtUtils::Install -e 'install([ from_to => {@ARGV}, verbose => '\''$(VERBINST)'\'', uninstall_shadows => '\''$(UNINST)'\'', dir_mode => '\''$(PERM_DIR)'\'' ]);' --
DOC_INSTALL = $(ABSPERLRUN) -MExtUtils::Command::MM -e 'perllocal_install' --
UNINSTALL = $(ABSPERLRUN) -MExtUtils::Command::MM -e 'uninstall' --
WARN_IF_OLD_PACKLIST = $(ABSPERLRUN) -MExtUtils::Command::MM -e 'warn_if_old_packlist' --
MACROSTART = 
MACROEND = 
USEMAKEFILE = -f
FIXIN = $(ABSPERLRUN) -MExtUtils::MY -e 'MY->fixin(shift)' --
CP_NONEMPTY = $(ABSPERLRUN) -MExtUtils::Command::MM -e 'cp_nonempty' --


# --- MakeMaker makemakerdflt section:
makemakerdflt : all
	$(NOECHO) $(NOOP)


# --- MakeMaker dist section:
TAR = COPY_EXTENDED_ATTRIBUTES_DISABLE=1 COPYFILE_DISABLE=1 tar
TARFLAGS = cvf
ZIP = zip
ZIPFLAGS = -r
COMPRESS = gzip --best
SUFFIX = .gz
SHAR = shar
PREOP = $(NOECHO) $(NOOP)
POSTOP = $(NOECHO) $(NOOP)
TO_UNIX = $(NOECHO) $(NOOP)
CI = ci -u
RCS_LABEL = rcs -Nv$(VERSION_SYM): -q
DIST_CP = best
DIST_DEFAULT = tardist
DISTNAME = NicToolServer
DISTVNAME = NicToolServer-2.35


# --- MakeMaker macro section:


# --- MakeMaker depend section:


# --- MakeMaker cflags section:


# --- MakeMaker const_loadlibs section:


# --- MakeMaker const_cccmd section:


# --- MakeMaker post_constants section:


# --- MakeMaker pasthru section:

PASTHRU = LIBPERL_A="$(LIBPERL_A)"\
	LINKTYPE="$(LINKTYPE)"\
	PREFIX="$(PREFIX)"\
	PASTHRU_DEFINE='$(DEFINE) $(PASTHRU_DEFINE)'\
	PASTHRU_INC='$(INC) $(PASTHRU_INC)'


# --- MakeMaker special_targets section:
.SUFFIXES : .xs .c .C .cpp .i .s .cxx .cc $(OBJ_EXT)

.PHONY: all config static dynamic test linkext manifest blibdirs clean realclean disttest distdir pure_all subdirs clean_subdirs makemakerdflt manifypods realclean_subdirs subdirs_dynamic subdirs_pure_nolink subdirs_static subdirs-test_dynamic subdirs-test_static test_dynamic test_static



# --- MakeMaker c_o section:


# --- MakeMaker xs_c section:


# --- MakeMaker xs_o section:


# --- MakeMaker top_targets section:
all :: pure_all manifypods
	$(NOECHO) $(NOOP)

pure_all :: config pm_to_blib subdirs linkext
	$(NOECHO) $(NOOP)

subdirs :: $(MYEXTLIB)
	$(NOECHO) $(NOOP)

config :: $(FIRST_MAKEFILE) blibdirs
	$(NOECHO) $(NOOP)

help :
	perldoc ExtUtils::MakeMaker


# --- MakeMaker blibdirs section:
blibdirs : $(INST_LIBDIR)$(DFSEP).exists $(INST_ARCHLIB)$(DFSEP).exists $(INST_AUTODIR)$(DFSEP).exists $(INST_ARCHAUTODIR)$(DFSEP).exists $(INST_BIN)$(DFSEP).exists $(INST_SCRIPT)$(DFSEP).exists $(INST_MAN1DIR)$(DFSEP).exists $(INST_MAN3DIR)$(DFSEP).exists
	$(NOECHO) $(NOOP)

# Backwards compat with 6.18 through 6.25
blibdirs.ts : blibdirs
	$(NOECHO) $(NOOP)

$(INST_LIBDIR)$(DFSEP).exists :: Makefile.PL
	$(NOECHO) $(MKPATH) $(INST_LIBDIR)
	$(NOECHO) $(CHMOD) $(PERM_DIR) $(INST_LIBDIR)
	$(NOECHO) $(TOUCH) $(INST_LIBDIR)$(DFSEP).exists

$(INST_ARCHLIB)$(DFSEP).exists :: Makefile.PL
	$(NOECHO) $(MKPATH) $(INST_ARCHLIB)
	$(NOECHO) $(CHMOD) $(PERM_DIR) $(INST_ARCHLIB)
	$(NOECHO) $(TOUCH) $(INST_ARCHLIB)$(DFSEP).exists

$(INST_AUTODIR)$(DFSEP).exists :: Makefile.PL
	$(NOECHO) $(MKPATH) $(INST_AUTODIR)
	$(NOECHO) $(CHMOD) $(PERM_DIR) $(INST_AUTODIR)
	$(NOECHO) $(TOUCH) $(INST_AUTODIR)$(DFSEP).exists

$(INST_ARCHAUTODIR)$(DFSEP).exists :: Makefile.PL
	$(NOECHO) $(MKPATH) $(INST_ARCHAUTODIR)
	$(NOECHO) $(CHMOD) $(PERM_DIR) $(INST_ARCHAUTODIR)
	$(NOECHO) $(TOUCH) $(INST_ARCHAUTODIR)$(DFSEP).exists

$(INST_BIN)$(DFSEP).exists :: Makefile.PL
	$(NOECHO) $(MKPATH) $(INST_BIN)
	$(NOECHO) $(CHMOD) $(PERM_DIR) $(INST_BIN)
	$(NOECHO) $(TOUCH) $(INST_BIN)$(DFSEP).exists

$(INST_SCRIPT)$(DFSEP).exists :: Makefile.PL
	$(NOECHO) $(MKPATH) $(INST_SCRIPT)
	$(NOECHO) $(CHMOD) $(PERM_DIR) $(INST_SCRIPT)
	$(NOECHO) $(TOUCH) $(INST_SCRIPT)$(DFSEP).exists

$(INST_MAN1DIR)$(DFSEP).exists :: Makefile.PL
	$(NOECHO) $(MKPATH) $(INST_MAN1DIR)
	$(NOECHO) $(CHMOD) $(PERM_DIR) $(INST_MAN1DIR)
	$(NOECHO) $(TOUCH) $(INST_MAN1DIR)$(DFSEP).exists

$(INST_MAN3DIR)$(DFSEP).exists :: Makefile.PL
	$(NOECHO) $(MKPATH) $(INST_MAN3DIR)
	$(NOECHO) $(CHMOD) $(PERM_DIR) $(INST_MAN3DIR)
	$(NOECHO) $(TOUCH) $(INST_MAN3DIR)$(DFSEP).exists



# --- MakeMaker linkext section:

linkext :: dynamic
	$(NOECHO) $(NOOP)


# --- MakeMaker dlsyms section:


# --- MakeMaker dynamic_bs section:

BOOTSTRAP =


# --- MakeMaker dynamic section:

dynamic :: $(FIRST_MAKEFILE) config $(INST_BOOT) $(INST_DYNAMIC)
	$(NOECHO) $(NOOP)


# --- MakeMaker dynamic_lib section:


# --- MakeMaker static section:

## $(INST_PM) has been moved to the all: target.
## It remains here for awhile to allow for old usage: "make static"
static :: $(FIRST_MAKEFILE) $(INST_STATIC)
	$(NOECHO) $(NOOP)


# --- MakeMaker static_lib section:


# --- MakeMaker manifypods section:

POD2MAN_EXE = $(PERLRUN) "-MExtUtils::Command::MM" -e pod2man "--"
POD2MAN = $(POD2MAN_EXE)


manifypods : pure_all config  \
	lib/NicToolServer.pm \
	lib/NicToolServer/Client.pm \
	lib/NicToolServer/Client/SOAP.pm \
	lib/NicToolServer/Export.pm \
	lib/NicToolServer/Export/BIND.pm \
	lib/NicToolServer/Export/BIND/nsupdate.pm \
	lib/NicToolServer/Export/Base.pm \
	lib/NicToolServer/Export/DynECT.pm \
	lib/NicToolServer/Export/Knot.pm \
	lib/NicToolServer/Export/MaraDNS.pm \
	lib/NicToolServer/Export/NSD.pm \
	lib/NicToolServer/Export/PowerDNS.pm \
	lib/NicToolServer/Export/tinydns.pm \
	lib/NicToolServer/Group.pm \
	lib/NicToolServer/Group/Sanity.pm \
	lib/NicToolServer/Import/BIND.pm \
	lib/NicToolServer/Import/Base.pm \
	lib/NicToolServer/Import/tinydns.pm \
	lib/NicToolServer/Nameserver.pm \
	lib/NicToolServer/Nameserver/Sanity.pm \
	lib/NicToolServer/Permission.pm \
	lib/NicToolServer/Response.pm \
	lib/NicToolServer/SOAP.pm \
	lib/NicToolServer/Session.pm \
	lib/NicToolServer/User.pm \
	lib/NicToolServer/User/Sanity.pm \
	lib/NicToolServer/Zone.pm \
	lib/NicToolServer/Zone/Record.pm \
	lib/NicToolServer/Zone/Record/Sanity.pm \
	lib/NicToolServer/Zone/Sanity.pm
	$(NOECHO) $(POD2MAN) --section=$(MAN3SECTION) --perm_rw=$(PERM_RW) -u \
	  lib/NicToolServer.pm $(INST_MAN3DIR)/NicToolServer.$(MAN3EXT) \
	  lib/NicToolServer/Client.pm $(INST_MAN3DIR)/NicToolServer::Client.$(MAN3EXT) \
	  lib/NicToolServer/Client/SOAP.pm $(INST_MAN3DIR)/NicToolServer::Client::SOAP.$(MAN3EXT) \
	  lib/NicToolServer/Export.pm $(INST_MAN3DIR)/NicToolServer::Export.$(MAN3EXT) \
	  lib/NicToolServer/Export/BIND.pm $(INST_MAN3DIR)/NicToolServer::Export::BIND.$(MAN3EXT) \
	  lib/NicToolServer/Export/BIND/nsupdate.pm $(INST_MAN3DIR)/NicToolServer::Export::BIND::nsupdate.$(MAN3EXT) \
	  lib/NicToolServer/Export/Base.pm $(INST_MAN3DIR)/NicToolServer::Export::Base.$(MAN3EXT) \
	  lib/NicToolServer/Export/DynECT.pm $(INST_MAN3DIR)/NicToolServer::Export::DynECT.$(MAN3EXT) \
	  lib/NicToolServer/Export/Knot.pm $(INST_MAN3DIR)/NicToolServer::Export::Knot.$(MAN3EXT) \
	  lib/NicToolServer/Export/MaraDNS.pm $(INST_MAN3DIR)/NicToolServer::Export::MaraDNS.$(MAN3EXT) \
	  lib/NicToolServer/Export/NSD.pm $(INST_MAN3DIR)/NicToolServer::Export::NSD.$(MAN3EXT) \
	  lib/NicToolServer/Export/PowerDNS.pm $(INST_MAN3DIR)/NicToolServer::Export::PowerDNS.$(MAN3EXT) \
	  lib/NicToolServer/Export/tinydns.pm $(INST_MAN3DIR)/NicToolServer::Export::tinydns.$(MAN3EXT) \
	  lib/NicToolServer/Group.pm $(INST_MAN3DIR)/NicToolServer::Group.$(MAN3EXT) \
	  lib/NicToolServer/Group/Sanity.pm $(INST_MAN3DIR)/NicToolServer::Group::Sanity.$(MAN3EXT) \
	  lib/NicToolServer/Import/BIND.pm $(INST_MAN3DIR)/NicToolServer::Import::BIND.$(MAN3EXT) \
	  lib/NicToolServer/Import/Base.pm $(INST_MAN3DIR)/NicToolServer::Import::Base.$(MAN3EXT) \
	  lib/NicToolServer/Import/tinydns.pm $(INST_MAN3DIR)/NicToolServer::Import::tinydns.$(MAN3EXT) \
	  lib/NicToolServer/Nameserver.pm $(INST_MAN3DIR)/NicToolServer::Nameserver.$(MAN3EXT) \
	  lib/NicToolServer/Nameserver/Sanity.pm $(INST_MAN3DIR)/NicToolServer::Nameserver::Sanity.$(MAN3EXT) \
	  lib/NicToolServer/Permission.pm $(INST_MAN3DIR)/NicToolServer::Permission.$(MAN3EXT) \
	  lib/NicToolServer/Response.pm $(INST_MAN3DIR)/NicToolServer::Response.$(MAN3EXT) \
	  lib/NicToolServer/SOAP.pm $(INST_MAN3DIR)/NicToolServer::SOAP.$(MAN3EXT) \
	  lib/NicToolServer/Session.pm $(INST_MAN3DIR)/NicToolServer::Session.$(MAN3EXT) \
	  lib/NicToolServer/User.pm $(INST_MAN3DIR)/NicToolServer::User.$(MAN3EXT) \
	  lib/NicToolServer/User/Sanity.pm $(INST_MAN3DIR)/NicToolServer::User::Sanity.$(MAN3EXT) \
	  lib/NicToolServer/Zone.pm $(INST_MAN3DIR)/NicToolServer::Zone.$(MAN3EXT) \
	  lib/NicToolServer/Zone/Record.pm $(INST_MAN3DIR)/NicToolServer::Zone::Record.$(MAN3EXT) \
	  lib/NicToolServer/Zone/Record/Sanity.pm $(INST_MAN3DIR)/NicToolServer::Zone::Record::Sanity.$(MAN3EXT) \
	  lib/NicToolServer/Zone/Sanity.pm $(INST_MAN3DIR)/NicToolServer::Zone::Sanity.$(MAN3EXT) 




# --- MakeMaker processPL section:


# --- MakeMaker installbin section:


# --- MakeMaker subdirs section:

# The default clean, realclean and test targets in this Makefile
# have automatically been given entries for each subdir.


subdirs ::
	$(NOECHO) cd api && $(MAKE) $(USEMAKEFILE) $(FIRST_MAKEFILE) all $(PASTHRU)


# --- MakeMaker clean_subdirs section:
clean_subdirs :
	$(ABSPERLRUN)  -e 'exit 0 unless chdir '\''api'\'';  system '\''$(MAKE) clean'\'' if -f '\''$(FIRST_MAKEFILE)'\'';' --


# --- MakeMaker clean section:

# Delete temporary files but do not touch installed files. We don't delete
# the Makefile here so a later make realclean still has a makefile to use.

clean :: clean_subdirs
	- $(RM_F) \
	  $(BASEEXT).bso $(BASEEXT).def \
	  $(BASEEXT).exp $(BASEEXT).x \
	  $(BOOTSTRAP) $(INST_ARCHAUTODIR)/extralibs.all \
	  $(INST_ARCHAUTODIR)/extralibs.ld $(MAKE_APERL_FILE) \
	  *$(LIB_EXT) *$(OBJ_EXT) \
	  *perl.core MYMETA.json \
	  MYMETA.yml blibdirs.ts \
	  core core.*perl.*.? \
	  core.[0-9] core.[0-9][0-9] \
	  core.[0-9][0-9][0-9] core.[0-9][0-9][0-9][0-9] \
	  core.[0-9][0-9][0-9][0-9][0-9] lib$(BASEEXT).def \
	  mon.out perl \
	  perl$(EXE_EXT) perl.exe \
	  perlmain.c pm_to_blib \
	  pm_to_blib.ts so_locations \
	  tmon.out 
	- $(RM_RF) \
	  blib 
	  $(NOECHO) $(RM_F) $(MAKEFILE_OLD)
	- $(MV) $(FIRST_MAKEFILE) $(MAKEFILE_OLD) $(DEV_NULL)


# --- MakeMaker realclean_subdirs section:
# so clean is forced to complete before realclean_subdirs runs
realclean_subdirs : clean
	- $(ABSPERLRUN)  -e 'chdir '\''api'\'';  system '\''$(MAKE) $(USEMAKEFILE) $(MAKEFILE_OLD) realclean'\'' if -f '\''$(MAKEFILE_OLD)'\'';' --
	- $(ABSPERLRUN)  -e 'chdir '\''api'\'';  system '\''$(MAKE) $(USEMAKEFILE) $(FIRST_MAKEFILE) realclean'\'' if -f '\''$(FIRST_MAKEFILE)'\'';' --


# --- MakeMaker realclean section:
# Delete temporary files (via clean) and also delete dist files
realclean purge :: realclean_subdirs
	- $(RM_F) \
	  $(FIRST_MAKEFILE) $(MAKEFILE_OLD) 
	- $(RM_RF) \
	  $(DISTVNAME) 


# --- MakeMaker metafile section:
metafile : create_distdir
	$(NOECHO) $(ECHO) Generating META.yml
	$(NOECHO) $(ECHO) '---' > META_new.yml
	$(NOECHO) $(ECHO) 'abstract: '\''NicTool API reference server'\''' >> META_new.yml
	$(NOECHO) $(ECHO) 'author:' >> META_new.yml
	$(NOECHO) $(ECHO) '  - '\''Matt Simerson <msimerson@cpan.org>, Damon Edwards, Abe Shelton, Greg Schueler'\''' >> META_new.yml
	$(NOECHO) $(ECHO) 'build_requires:' >> META_new.yml
	$(NOECHO) $(ECHO) '  Exporter: '\''0'\''' >> META_new.yml
	$(NOECHO) $(ECHO) '  ExtUtils::MakeMaker: '\''0'\''' >> META_new.yml
	$(NOECHO) $(ECHO) '  Test: '\''0'\''' >> META_new.yml
	$(NOECHO) $(ECHO) '  Test::More: '\''0'\''' >> META_new.yml
	$(NOECHO) $(ECHO) '  Test::Output: '\''0'\''' >> META_new.yml
	$(NOECHO) $(ECHO) 'configure_requires:' >> META_new.yml
	$(NOECHO) $(ECHO) '  ExtUtils::MakeMaker: '\''0'\''' >> META_new.yml
	$(NOECHO) $(ECHO) 'dynamic_config: 1' >> META_new.yml
	$(NOECHO) $(ECHO) 'generated_by: '\''ExtUtils::MakeMaker version 7.76, CPAN::Meta::Converter version 2.150013'\''' >> META_new.yml
	$(NOECHO) $(ECHO) 'license: open_source' >> META_new.yml
	$(NOECHO) $(ECHO) 'meta-spec:' >> META_new.yml
	$(NOECHO) $(ECHO) '  url: http://module-build.sourceforge.net/META-spec-v1.4.html' >> META_new.yml
	$(NOECHO) $(ECHO) '  version: '\''1.4'\''' >> META_new.yml
	$(NOECHO) $(ECHO) 'name: NicToolServer' >> META_new.yml
	$(NOECHO) $(ECHO) 'no_index:' >> META_new.yml
	$(NOECHO) $(ECHO) '  directory:' >> META_new.yml
	$(NOECHO) $(ECHO) '    - t' >> META_new.yml
	$(NOECHO) $(ECHO) '    - inc' >> META_new.yml
	$(NOECHO) $(ECHO) 'requires:' >> META_new.yml
	$(NOECHO) $(ECHO) '  Apache::DBI: '\''0'\''' >> META_new.yml
	$(NOECHO) $(ECHO) '  BIND::Conf_Parser: '\''0'\''' >> META_new.yml
	$(NOECHO) $(ECHO) '  CGI: '\''4.21'\''' >> META_new.yml
	$(NOECHO) $(ECHO) '  Crypt::KeyDerivation: '\''0'\''' >> META_new.yml
	$(NOECHO) $(ECHO) '  Crypt::Mac::HMAC: '\''0'\''' >> META_new.yml
	$(NOECHO) $(ECHO) '  CryptX: '\''0.021'\''' >> META_new.yml
	$(NOECHO) $(ECHO) '  Cwd: '\''0'\''' >> META_new.yml
	$(NOECHO) $(ECHO) '  DBD::MariaDB: '\''0'\''' >> META_new.yml
	$(NOECHO) $(ECHO) '  DBI: '\''1.20'\''' >> META_new.yml
	$(NOECHO) $(ECHO) '  DBIx::Simple: '\''0'\''' >> META_new.yml
	$(NOECHO) $(ECHO) '  Data::Dumper: '\''0'\''' >> META_new.yml
	$(NOECHO) $(ECHO) '  English: '\''0'\''' >> META_new.yml
	$(NOECHO) $(ECHO) '  File::Copy: '\''0'\''' >> META_new.yml
	$(NOECHO) $(ECHO) '  File::Path: '\''0'\''' >> META_new.yml
	$(NOECHO) $(ECHO) '  HTML::Parser: '\''0'\''' >> META_new.yml
	$(NOECHO) $(ECHO) '  IO::File: '\''0'\''' >> META_new.yml
	$(NOECHO) $(ECHO) '  JSON: '\''0'\''' >> META_new.yml
	$(NOECHO) $(ECHO) '  LWP::UserAgent: '\''0'\''' >> META_new.yml
	$(NOECHO) $(ECHO) '  MIME::Base32: '\''0'\''' >> META_new.yml
	$(NOECHO) $(ECHO) '  MIME::Base64: '\''0'\''' >> META_new.yml
	$(NOECHO) $(ECHO) '  Net::DNS::ZoneFile: '\''0'\''' >> META_new.yml
	$(NOECHO) $(ECHO) '  Net::IP: '\''0'\''' >> META_new.yml
	$(NOECHO) $(ECHO) '  Params::Validate: '\''0.8'\''' >> META_new.yml
	$(NOECHO) $(ECHO) '  RPC::XML: '\''0'\''' >> META_new.yml
	$(NOECHO) $(ECHO) '  RPC::XML::Parser: '\''0'\''' >> META_new.yml
	$(NOECHO) $(ECHO) '  SOAP::Lite: '\''0.51'\''' >> META_new.yml
	$(NOECHO) $(ECHO) '  Scalar::Util: '\''0'\''' >> META_new.yml
	$(NOECHO) $(ECHO) '  Time::HiRes: '\''1.9'\''' >> META_new.yml
	$(NOECHO) $(ECHO) '  Time::Local: '\''0'\''' >> META_new.yml
	$(NOECHO) $(ECHO) '  Time::TAI64: '\''2'\''' >> META_new.yml
	$(NOECHO) $(ECHO) '  XML::Parser: '\''0'\''' >> META_new.yml
	$(NOECHO) $(ECHO) '  constant: '\''0'\''' >> META_new.yml
	$(NOECHO) $(ECHO) '  lib: '\''0'\''' >> META_new.yml
	$(NOECHO) $(ECHO) '  parent: '\''0.2'\''' >> META_new.yml
	$(NOECHO) $(ECHO) '  strict: '\''0'\''' >> META_new.yml
	$(NOECHO) $(ECHO) '  vars: '\''0'\''' >> META_new.yml
	$(NOECHO) $(ECHO) '  warnings: '\''0'\''' >> META_new.yml
	$(NOECHO) $(ECHO) 'version: '\''2.35'\''' >> META_new.yml
	$(NOECHO) $(ECHO) 'x_serialization_backend: '\''CPAN::Meta::YAML version 0.020'\''' >> META_new.yml
	-$(NOECHO) $(MV) META_new.yml $(DISTVNAME)/META.yml
	$(NOECHO) $(ECHO) Generating META.json
	$(NOECHO) $(ECHO) '{' > META_new.json
	$(NOECHO) $(ECHO) '   "abstract" : "NicTool API reference server",' >> META_new.json
	$(NOECHO) $(ECHO) '   "author" : [' >> META_new.json
	$(NOECHO) $(ECHO) '      "Matt Simerson <msimerson@cpan.org>, Damon Edwards, Abe Shelton, Greg Schueler"' >> META_new.json
	$(NOECHO) $(ECHO) '   ],' >> META_new.json
	$(NOECHO) $(ECHO) '   "dynamic_config" : 1,' >> META_new.json
	$(NOECHO) $(ECHO) '   "generated_by" : "ExtUtils::MakeMaker version 7.76, CPAN::Meta::Converter version 2.150013",' >> META_new.json
	$(NOECHO) $(ECHO) '   "license" : [' >> META_new.json
	$(NOECHO) $(ECHO) '      "open_source"' >> META_new.json
	$(NOECHO) $(ECHO) '   ],' >> META_new.json
	$(NOECHO) $(ECHO) '   "meta-spec" : {' >> META_new.json
	$(NOECHO) $(ECHO) '      "url" : "http://search.cpan.org/perldoc?CPAN::Meta::Spec",' >> META_new.json
	$(NOECHO) $(ECHO) '      "version" : 2' >> META_new.json
	$(NOECHO) $(ECHO) '   },' >> META_new.json
	$(NOECHO) $(ECHO) '   "name" : "NicToolServer",' >> META_new.json
	$(NOECHO) $(ECHO) '   "no_index" : {' >> META_new.json
	$(NOECHO) $(ECHO) '      "directory" : [' >> META_new.json
	$(NOECHO) $(ECHO) '         "t",' >> META_new.json
	$(NOECHO) $(ECHO) '         "inc"' >> META_new.json
	$(NOECHO) $(ECHO) '      ]' >> META_new.json
	$(NOECHO) $(ECHO) '   },' >> META_new.json
	$(NOECHO) $(ECHO) '   "prereqs" : {' >> META_new.json
	$(NOECHO) $(ECHO) '      "build" : {' >> META_new.json
	$(NOECHO) $(ECHO) '         "requires" : {' >> META_new.json
	$(NOECHO) $(ECHO) '            "ExtUtils::MakeMaker" : "0"' >> META_new.json
	$(NOECHO) $(ECHO) '         }' >> META_new.json
	$(NOECHO) $(ECHO) '      },' >> META_new.json
	$(NOECHO) $(ECHO) '      "configure" : {' >> META_new.json
	$(NOECHO) $(ECHO) '         "requires" : {' >> META_new.json
	$(NOECHO) $(ECHO) '            "ExtUtils::MakeMaker" : "0"' >> META_new.json
	$(NOECHO) $(ECHO) '         }' >> META_new.json
	$(NOECHO) $(ECHO) '      },' >> META_new.json
	$(NOECHO) $(ECHO) '      "runtime" : {' >> META_new.json
	$(NOECHO) $(ECHO) '         "requires" : {' >> META_new.json
	$(NOECHO) $(ECHO) '            "Apache::DBI" : "0",' >> META_new.json
	$(NOECHO) $(ECHO) '            "BIND::Conf_Parser" : "0",' >> META_new.json
	$(NOECHO) $(ECHO) '            "CGI" : "4.21",' >> META_new.json
	$(NOECHO) $(ECHO) '            "Crypt::KeyDerivation" : "0",' >> META_new.json
	$(NOECHO) $(ECHO) '            "Crypt::Mac::HMAC" : "0",' >> META_new.json
	$(NOECHO) $(ECHO) '            "CryptX" : "0.021",' >> META_new.json
	$(NOECHO) $(ECHO) '            "Cwd" : "0",' >> META_new.json
	$(NOECHO) $(ECHO) '            "DBD::MariaDB" : "0",' >> META_new.json
	$(NOECHO) $(ECHO) '            "DBI" : "1.20",' >> META_new.json
	$(NOECHO) $(ECHO) '            "DBIx::Simple" : "0",' >> META_new.json
	$(NOECHO) $(ECHO) '            "Data::Dumper" : "0",' >> META_new.json
	$(NOECHO) $(ECHO) '            "English" : "0",' >> META_new.json
	$(NOECHO) $(ECHO) '            "File::Copy" : "0",' >> META_new.json
	$(NOECHO) $(ECHO) '            "File::Path" : "0",' >> META_new.json
	$(NOECHO) $(ECHO) '            "HTML::Parser" : "0",' >> META_new.json
	$(NOECHO) $(ECHO) '            "IO::File" : "0",' >> META_new.json
	$(NOECHO) $(ECHO) '            "JSON" : "0",' >> META_new.json
	$(NOECHO) $(ECHO) '            "LWP::UserAgent" : "0",' >> META_new.json
	$(NOECHO) $(ECHO) '            "MIME::Base32" : "0",' >> META_new.json
	$(NOECHO) $(ECHO) '            "MIME::Base64" : "0",' >> META_new.json
	$(NOECHO) $(ECHO) '            "Net::DNS::ZoneFile" : "0",' >> META_new.json
	$(NOECHO) $(ECHO) '            "Net::IP" : "0",' >> META_new.json
	$(NOECHO) $(ECHO) '            "Params::Validate" : "0.8",' >> META_new.json
	$(NOECHO) $(ECHO) '            "RPC::XML" : "0",' >> META_new.json
	$(NOECHO) $(ECHO) '            "RPC::XML::Parser" : "0",' >> META_new.json
	$(NOECHO) $(ECHO) '            "SOAP::Lite" : "0.51",' >> META_new.json
	$(NOECHO) $(ECHO) '            "Scalar::Util" : "0",' >> META_new.json
	$(NOECHO) $(ECHO) '            "Time::HiRes" : "1.9",' >> META_new.json
	$(NOECHO) $(ECHO) '            "Time::Local" : "0",' >> META_new.json
	$(NOECHO) $(ECHO) '            "Time::TAI64" : "2",' >> META_new.json
	$(NOECHO) $(ECHO) '            "XML::Parser" : "0",' >> META_new.json
	$(NOECHO) $(ECHO) '            "constant" : "0",' >> META_new.json
	$(NOECHO) $(ECHO) '            "lib" : "0",' >> META_new.json
	$(NOECHO) $(ECHO) '            "parent" : "0.2",' >> META_new.json
	$(NOECHO) $(ECHO) '            "strict" : "0",' >> META_new.json
	$(NOECHO) $(ECHO) '            "vars" : "0",' >> META_new.json
	$(NOECHO) $(ECHO) '            "warnings" : "0"' >> META_new.json
	$(NOECHO) $(ECHO) '         }' >> META_new.json
	$(NOECHO) $(ECHO) '      },' >> META_new.json
	$(NOECHO) $(ECHO) '      "test" : {' >> META_new.json
	$(NOECHO) $(ECHO) '         "requires" : {' >> META_new.json
	$(NOECHO) $(ECHO) '            "Exporter" : "0",' >> META_new.json
	$(NOECHO) $(ECHO) '            "Test" : "0",' >> META_new.json
	$(NOECHO) $(ECHO) '            "Test::More" : "0",' >> META_new.json
	$(NOECHO) $(ECHO) '            "Test::Output" : "0"' >> META_new.json
	$(NOECHO) $(ECHO) '         }' >> META_new.json
	$(NOECHO) $(ECHO) '      }' >> META_new.json
	$(NOECHO) $(ECHO) '   },' >> META_new.json
	$(NOECHO) $(ECHO) '   "release_status" : "stable",' >> META_new.json
	$(NOECHO) $(ECHO) '   "version" : "2.35",' >> META_new.json
	$(NOECHO) $(ECHO) '   "x_serialization_backend" : "JSON::PP version 4.06"' >> META_new.json
	$(NOECHO) $(ECHO) '}' >> META_new.json
	-$(NOECHO) $(MV) META_new.json $(DISTVNAME)/META.json


# --- MakeMaker signature section:
signature :
	cpansign -s


# --- MakeMaker dist_basics section:
distclean :: realclean distcheck
	$(NOECHO) $(NOOP)

distcheck :
	$(PERLRUN) "-MExtUtils::Manifest=fullcheck" -e fullcheck

skipcheck :
	$(PERLRUN) "-MExtUtils::Manifest=skipcheck" -e skipcheck

manifest :
	$(PERLRUN) "-MExtUtils::Manifest=mkmanifest" -e mkmanifest

veryclean : realclean
	$(RM_F) *~ */*~ *.orig */*.orig *.bak */*.bak *.old */*.old



# --- MakeMaker dist_core section:

dist : $(DIST_DEFAULT) $(FIRST_MAKEFILE)
	$(NOECHO) $(ABSPERLRUN) -l -e 'print '\''Warning: Makefile possibly out of date with $(VERSION_FROM)'\''' \
	  -e '    if -e '\''$(VERSION_FROM)'\'' and -M '\''$(VERSION_FROM)'\'' < -M '\''$(FIRST_MAKEFILE)'\'';' --

tardist : $(DISTVNAME).tar$(SUFFIX)
	$(NOECHO) $(NOOP)

uutardist : $(DISTVNAME).tar$(SUFFIX)
	uuencode $(DISTVNAME).tar$(SUFFIX) $(DISTVNAME).tar$(SUFFIX) > $(DISTVNAME).tar$(SUFFIX)_uu
	$(NOECHO) $(ECHO) 'Created $(DISTVNAME).tar$(SUFFIX)_uu'

$(DISTVNAME).tar$(SUFFIX) : distdir
	$(PREOP)
	$(TO_UNIX)
	$(TAR) $(TARFLAGS) $(DISTVNAME).tar $(DISTVNAME)
	$(RM_RF) $(DISTVNAME)
	$(COMPRESS) $(DISTVNAME).tar
	$(NOECHO) $(ECHO) 'Created $(DISTVNAME).tar$(SUFFIX)'
	$(POSTOP)

zipdist : $(DISTVNAME).zip
	$(NOECHO) $(NOOP)

$(DISTVNAME).zip : distdir
	$(PREOP)
	$(ZIP) $(ZIPFLAGS) $(DISTVNAME).zip $(DISTVNAME)
	$(RM_RF) $(DISTVNAME)
	$(NOECHO) $(ECHO) 'Created $(DISTVNAME).zip'
	$(POSTOP)

shdist : distdir
	$(PREOP)
	$(SHAR) $(DISTVNAME) > $(DISTVNAME).shar
	$(RM_RF) $(DISTVNAME)
	$(NOECHO) $(ECHO) 'Created $(DISTVNAME).shar'
	$(POSTOP)


# --- MakeMaker distdir section:
create_distdir :
	$(RM_RF) $(DISTVNAME)
	$(PERLRUN) "-MExtUtils::Manifest=manicopy,maniread" \
		-e "manicopy(maniread(),'$(DISTVNAME)', '$(DIST_CP)');"

distdir : create_distdir distmeta 
	$(NOECHO) $(NOOP)



# --- MakeMaker dist_test section:
disttest : distdir
	cd $(DISTVNAME) && $(ABSPERLRUN) Makefile.PL 
	cd $(DISTVNAME) && $(MAKE) $(PASTHRU)
	cd $(DISTVNAME) && $(MAKE) test $(PASTHRU)



# --- MakeMaker dist_ci section:
ci :
	$(ABSPERLRUN) -MExtUtils::Manifest=maniread -e '@all = sort keys %{ maniread() };' \
	  -e 'print(qq{Executing $(CI) @all\n});' \
	  -e 'system(qq{$(CI) @all}) == 0 or die $$!;' \
	  -e 'print(qq{Executing $(RCS_LABEL) ...\n});' \
	  -e 'system(qq{$(RCS_LABEL) @all}) == 0 or die $$!;' --


# --- MakeMaker distmeta section:
distmeta : create_distdir metafile
	$(NOECHO) cd $(DISTVNAME) && $(ABSPERLRUN) -MExtUtils::Manifest=maniadd -e 'exit unless -e q{META.yml};' \
	  -e 'eval { maniadd({q{META.yml} => q{Module YAML meta-data (added by MakeMaker)}}) }' \
	  -e '    or die "Could not add META.yml to MANIFEST: $${'\''@'\''}"' --
	$(NOECHO) cd $(DISTVNAME) && $(ABSPERLRUN) -MExtUtils::Manifest=maniadd -e 'exit unless -f q{META.json};' \
	  -e 'eval { maniadd({q{META.json} => q{Module JSON meta-data (added by MakeMaker)}}) }' \
	  -e '    or die "Could not add META.json to MANIFEST: $${'\''@'\''}"' --



# --- MakeMaker distsignature section:
distsignature : distmeta
	$(NOECHO) cd $(DISTVNAME) && $(ABSPERLRUN) -MExtUtils::Manifest=maniadd -e 'eval { maniadd({q{SIGNATURE} => q{Public-key signature (added by MakeMaker)}}) }' \
	  -e '    or die "Could not add SIGNATURE to MANIFEST: $${'\''@'\''}"' --
	$(NOECHO) cd $(DISTVNAME) && $(TOUCH) SIGNATURE
	cd $(DISTVNAME) && cpansign -s



# --- MakeMaker install section:

install :: pure_install doc_install
	$(NOECHO) $(NOOP)

install_perl :: pure_perl_install doc_perl_install
	$(NOECHO) $(NOOP)

install_site :: pure_site_install doc_site_install
	$(NOECHO) $(NOOP)

install_vendor :: pure_vendor_install doc_vendor_install
	$(NOECHO) $(NOOP)

pure_install :: pure_$(INSTALLDIRS)_install
	$(NOECHO) $(NOOP)

doc_install :: doc_$(INSTALLDIRS)_install
	$(NOECHO) $(NOOP)

pure__install : pure_site_install
	$(NOECHO) $(ECHO) INSTALLDIRS not defined, defaulting to INSTALLDIRS=site

doc__install : doc_site_install
	$(NOECHO) $(ECHO) INSTALLDIRS not defined, defaulting to INSTALLDIRS=site

pure_perl_install :: all
	$(NOECHO) $(MOD_INSTALL) \
		read "$(PERL_ARCHLIB)/auto/$(FULLEXT)/.packlist" \
		write "$(DESTINSTALLARCHLIB)/auto/$(FULLEXT)/.packlist" \
		"$(INST_LIB)" "$(DESTINSTALLPRIVLIB)" \
		"$(INST_ARCHLIB)" "$(DESTINSTALLARCHLIB)" \
		"$(INST_BIN)" "$(DESTINSTALLBIN)" \
		"$(INST_SCRIPT)" "$(DESTINSTALLSCRIPT)" \
		"$(INST_MAN1DIR)" "$(DESTINSTALLMAN1DIR)" \
		"$(INST_MAN3DIR)" "$(DESTINSTALLMAN3DIR)"
	$(NOECHO) $(WARN_IF_OLD_PACKLIST) \
		"$(SITEARCHEXP)/auto/$(FULLEXT)"


pure_site_install :: all
	$(NOECHO) $(MOD_INSTALL) \
		read "$(SITEARCHEXP)/auto/$(FULLEXT)/.packlist" \
		write "$(DESTINSTALLSITEARCH)/auto/$(FULLEXT)/.packlist" \
		"$(INST_LIB)" "$(DESTINSTALLSITELIB)" \
		"$(INST_ARCHLIB)" "$(DESTINSTALLSITEARCH)" \
		"$(INST_BIN)" "$(DESTINSTALLSITEBIN)" \
		"$(INST_SCRIPT)" "$(DESTINSTALLSITESCRIPT)" \
		"$(INST_MAN1DIR)" "$(DESTINSTALLSITEMAN1DIR)" \
		"$(INST_MAN3DIR)" "$(DESTINSTALLSITEMAN3DIR)"
	$(NOECHO) $(WARN_IF_OLD_PACKLIST) \
		"$(PERL_ARCHLIB)/auto/$(FULLEXT)"

pure_vendor_install :: all
	$(NOECHO) $(MOD_INSTALL) \
		read "$(VENDORARCHEXP)/auto/$(FULLEXT)/.packlist" \
		write "$(DESTINSTALLVENDORARCH)/auto/$(FULLEXT)/.packlist" \
		"$(INST_LIB)" "$(DESTINSTALLVENDORLIB)" \
		"$(INST_ARCHLIB)" "$(DESTINSTALLVENDORARCH)" \
		"$(INST_BIN)" "$(DESTINSTALLVENDORBIN)" \
		"$(INST_SCRIPT)" "$(DESTINSTALLVENDORSCRIPT)" \
		"$(INST_MAN1DIR)" "$(DESTINSTALLVENDORMAN1DIR)" \
		"$(INST_MAN3DIR)" "$(DESTINSTALLVENDORMAN3DIR)"


doc_perl_install :: all
	$(NOECHO) $(ECHO) Appending installation info to "$(DESTINSTALLARCHLIB)/perllocal.pod"
	-$(NOECHO) $(MKPATH) "$(DESTINSTALLARCHLIB)"
	-$(NOECHO) $(DOC_INSTALL) \
		"Module" "$(NAME)" \
		"installed into" "$(INSTALLPRIVLIB)" \
		LINKTYPE "$(LINKTYPE)" \
		VERSION "$(VERSION)" \
		EXE_FILES "$(EXE_FILES)" \
		>> "$(DESTINSTALLARCHLIB)/perllocal.pod"

doc_site_install :: all
	$(NOECHO) $(ECHO) Appending installation info to "$(DESTINSTALLARCHLIB)/perllocal.pod"
	-$(NOECHO) $(MKPATH) "$(DESTINSTALLARCHLIB)"
	-$(NOECHO) $(DOC_INSTALL) \
		"Module" "$(NAME)" \
		"installed into" "$(INSTALLSITELIB)" \
		LINKTYPE "$(LINKTYPE)" \
		VERSION "$(VERSION)" \
		EXE_FILES "$(EXE_FILES)" \
		>> "$(DESTINSTALLARCHLIB)/perllocal.pod"

doc_vendor_install :: all
	$(NOECHO) $(ECHO) Appending installation info to "$(DESTINSTALLARCHLIB)/perllocal.pod"
	-$(NOECHO) $(MKPATH) "$(DESTINSTALLARCHLIB)"
	-$(NOECHO) $(DOC_INSTALL) \
		"Module" "$(NAME)" \
		"installed into" "$(INSTALLVENDORLIB)" \
		LINKTYPE "$(LINKTYPE)" \
		VERSION "$(VERSION)" \
		EXE_FILES "$(EXE_FILES)" \
		>> "$(DESTINSTALLARCHLIB)/perllocal.pod"


uninstall :: uninstall_from_$(INSTALLDIRS)dirs
	$(NOECHO) $(NOOP)

uninstall_from_perldirs ::
	$(NOECHO) $(UNINSTALL) "$(PERL_ARCHLIB)/auto/$(FULLEXT)/.packlist"

uninstall_from_sitedirs ::
	$(NOECHO) $(UNINSTALL) "$(SITEARCHEXP)/auto/$(FULLEXT)/.packlist"

uninstall_from_vendordirs ::
	$(NOECHO) $(UNINSTALL) "$(VENDORARCHEXP)/auto/$(FULLEXT)/.packlist"


# --- MakeMaker force section:
# Phony target to force checking subdirectories.
FORCE :
	$(NOECHO) $(NOOP)


# --- MakeMaker perldepend section:


# --- MakeMaker makefile section:
# We take a very conservative approach here, but it's worth it.
# We move Makefile to Makefile.old here to avoid gnu make looping.
$(FIRST_MAKEFILE) : Makefile.PL $(CONFIGDEP)
	$(NOECHO) $(ECHO) "Makefile out-of-date with respect to $?"
	$(NOECHO) $(ECHO) "Cleaning current config before rebuilding Makefile..."
	-$(NOECHO) $(RM_F) $(MAKEFILE_OLD)
	-$(NOECHO) $(MV)   $(FIRST_MAKEFILE) $(MAKEFILE_OLD)
	- $(MAKE) $(USEMAKEFILE) $(MAKEFILE_OLD) clean $(DEV_NULL)
	$(PERLRUN) Makefile.PL 
	$(NOECHO) $(ECHO) "==> Your Makefile has been rebuilt. <=="
	$(NOECHO) $(ECHO) "==> Please rerun the $(MAKE) command.  <=="
	$(FALSE)



# --- MakeMaker staticmake section:

# --- MakeMaker makeaperl section ---
MAP_TARGET    = perl
FULLPERL      = "/opt/local/bin/perl5.34"
MAP_PERLINC   = "-Iblib/arch" "-Iblib/lib" "-I/opt/local/lib/perl5/5.34/darwin-thread-multi-2level" "-I/opt/local/lib/perl5/5.34"

$(MAP_TARGET) :: $(MAKE_APERL_FILE)
	$(MAKE) $(USEMAKEFILE) $(MAKE_APERL_FILE) $@

$(MAKE_APERL_FILE) : static $(FIRST_MAKEFILE) pm_to_blib
	$(NOECHO) $(ECHO) Writing \"$(MAKE_APERL_FILE)\" for this $(MAP_TARGET)
	$(NOECHO) $(PERLRUNINST) \
		Makefile.PL DIR="api" \
		MAKEFILE=$(MAKE_APERL_FILE) LINKTYPE=static \
		MAKEAPERL=1 NORECURS=1 CCCDLFLAGS=


# --- MakeMaker test section:
TEST_VERBOSE=0
TEST_TYPE=test_$(LINKTYPE)
TEST_FILE = test.pl
TEST_FILES = t/*.t
TESTDB_SW = -d

testdb :: testdb_$(LINKTYPE)
	$(NOECHO) $(NOOP)

test :: $(TEST_TYPE)
	$(NOECHO) $(NOOP)

# Occasionally we may face this degenerate target:
test_ : test_dynamic
	$(NOECHO) $(NOOP)

subdirs-test_dynamic :: dynamic pure_all
	$(NOECHO) cd api && $(MAKE) test_dynamic $(PASTHRU)

test_dynamic :: subdirs-test_dynamic
	PERL_DL_NONLAZY=1 $(FULLPERLRUN) "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness($(TEST_VERBOSE), '$(INST_LIB)', '$(INST_ARCHLIB)')" $(TEST_FILES)

testdb_dynamic :: dynamic pure_all
	PERL_DL_NONLAZY=1 $(FULLPERLRUN) $(TESTDB_SW) "-I$(INST_LIB)" "-I$(INST_ARCHLIB)" $(TEST_FILE)

subdirs-test_static :: static pure_all
	$(NOECHO) cd api && $(MAKE) test_static $(PASTHRU)

test_static :: subdirs-test_static
	PERL_DL_NONLAZY=1 $(FULLPERLRUN) "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness($(TEST_VERBOSE), '$(INST_LIB)', '$(INST_ARCHLIB)')" $(TEST_FILES)

testdb_static :: static pure_all
	PERL_DL_NONLAZY=1 $(FULLPERLRUN) $(TESTDB_SW) "-I$(INST_LIB)" "-I$(INST_ARCHLIB)" $(TEST_FILE)



# --- MakeMaker ppd section:
# Creates a PPD (Perl Package Description) for a binary distribution.
ppd :
	$(NOECHO) $(ECHO) '<SOFTPKG NAME="NicToolServer" VERSION="2.35">' > NicToolServer.ppd
	$(NOECHO) $(ECHO) '    <ABSTRACT>NicTool API reference server</ABSTRACT>' >> NicToolServer.ppd
	$(NOECHO) $(ECHO) '    <AUTHOR>Matt Simerson &lt;msimerson@cpan.org&gt;, Damon Edwards, Abe Shelton, Greg Schueler</AUTHOR>' >> NicToolServer.ppd
	$(NOECHO) $(ECHO) '    <IMPLEMENTATION>' >> NicToolServer.ppd
	$(NOECHO) $(ECHO) '        <REQUIRE NAME="Apache::DBI" />' >> NicToolServer.ppd
	$(NOECHO) $(ECHO) '        <REQUIRE NAME="BIND::Conf_Parser" />' >> NicToolServer.ppd
	$(NOECHO) $(ECHO) '        <REQUIRE NAME="CGI::" VERSION="4.21" />' >> NicToolServer.ppd
	$(NOECHO) $(ECHO) '        <REQUIRE NAME="Crypt::KeyDerivation" />' >> NicToolServer.ppd
	$(NOECHO) $(ECHO) '        <REQUIRE NAME="Crypt::Mac::HMAC" />' >> NicToolServer.ppd
	$(NOECHO) $(ECHO) '        <REQUIRE NAME="CryptX::" VERSION="0.021" />' >> NicToolServer.ppd
	$(NOECHO) $(ECHO) '        <REQUIRE NAME="Cwd::" />' >> NicToolServer.ppd
	$(NOECHO) $(ECHO) '        <REQUIRE NAME="DBD::MariaDB" />' >> NicToolServer.ppd
	$(NOECHO) $(ECHO) '        <REQUIRE NAME="DBI::" VERSION="1.20" />' >> NicToolServer.ppd
	$(NOECHO) $(ECHO) '        <REQUIRE NAME="DBIx::Simple" />' >> NicToolServer.ppd
	$(NOECHO) $(ECHO) '        <REQUIRE NAME="Data::Dumper" />' >> NicToolServer.ppd
	$(NOECHO) $(ECHO) '        <REQUIRE NAME="English::" />' >> NicToolServer.ppd
	$(NOECHO) $(ECHO) '        <REQUIRE NAME="File::Copy" />' >> NicToolServer.ppd
	$(NOECHO) $(ECHO) '        <REQUIRE NAME="File::Path" />' >> NicToolServer.ppd
	$(NOECHO) $(ECHO) '        <REQUIRE NAME="HTML::Parser" />' >> NicToolServer.ppd
	$(NOECHO) $(ECHO) '        <REQUIRE NAME="IO::File" />' >> NicToolServer.ppd
	$(NOECHO) $(ECHO) '        <REQUIRE NAME="JSON::" />' >> NicToolServer.ppd
	$(NOECHO) $(ECHO) '        <REQUIRE NAME="LWP::UserAgent" />' >> NicToolServer.ppd
	$(NOECHO) $(ECHO) '        <REQUIRE NAME="MIME::Base32" />' >> NicToolServer.ppd
	$(NOECHO) $(ECHO) '        <REQUIRE NAME="MIME::Base64" />' >> NicToolServer.ppd
	$(NOECHO) $(ECHO) '        <REQUIRE NAME="Net::DNS::ZoneFile" />' >> NicToolServer.ppd
	$(NOECHO) $(ECHO) '        <REQUIRE NAME="Net::IP" />' >> NicToolServer.ppd
	$(NOECHO) $(ECHO) '        <REQUIRE NAME="Params::Validate" VERSION="0.8" />' >> NicToolServer.ppd
	$(NOECHO) $(ECHO) '        <REQUIRE NAME="RPC::XML" />' >> NicToolServer.ppd
	$(NOECHO) $(ECHO) '        <REQUIRE NAME="RPC::XML::Parser" />' >> NicToolServer.ppd
	$(NOECHO) $(ECHO) '        <REQUIRE NAME="SOAP::Lite" VERSION="0.51" />' >> NicToolServer.ppd
	$(NOECHO) $(ECHO) '        <REQUIRE NAME="Scalar::Util" />' >> NicToolServer.ppd
	$(NOECHO) $(ECHO) '        <REQUIRE NAME="Time::HiRes" VERSION="1.9" />' >> NicToolServer.ppd
	$(NOECHO) $(ECHO) '        <REQUIRE NAME="Time::Local" />' >> NicToolServer.ppd
	$(NOECHO) $(ECHO) '        <REQUIRE NAME="Time::TAI64" VERSION="2" />' >> NicToolServer.ppd
	$(NOECHO) $(ECHO) '        <REQUIRE NAME="XML::Parser" />' >> NicToolServer.ppd
	$(NOECHO) $(ECHO) '        <REQUIRE NAME="constant::" />' >> NicToolServer.ppd
	$(NOECHO) $(ECHO) '        <REQUIRE NAME="lib::" />' >> NicToolServer.ppd
	$(NOECHO) $(ECHO) '        <REQUIRE NAME="parent::" VERSION="0.2" />' >> NicToolServer.ppd
	$(NOECHO) $(ECHO) '        <REQUIRE NAME="strict::" />' >> NicToolServer.ppd
	$(NOECHO) $(ECHO) '        <REQUIRE NAME="vars::" />' >> NicToolServer.ppd
	$(NOECHO) $(ECHO) '        <REQUIRE NAME="warnings::" />' >> NicToolServer.ppd
	$(NOECHO) $(ECHO) '        <ARCHITECTURE NAME="darwin-thread-multi-2level-5.34" />' >> NicToolServer.ppd
	$(NOECHO) $(ECHO) '        <CODEBASE HREF="" />' >> NicToolServer.ppd
	$(NOECHO) $(ECHO) '    </IMPLEMENTATION>' >> NicToolServer.ppd
	$(NOECHO) $(ECHO) '</SOFTPKG>' >> NicToolServer.ppd


# --- MakeMaker pm_to_blib section:

pm_to_blib : $(FIRST_MAKEFILE) $(TO_INST_PM)
	$(NOECHO) $(ABSPERLRUN) -MExtUtils::Install -e '$$i=0; $$n=$$#ARGV; $$i++ until $$i > $$n or $$ARGV[$$i] eq q{--};' \
	  -e 'die q{Failed to find -- in }.join(q{|},@ARGV) if $$i > $$n;' \
	  -e '@parts=splice @ARGV,0,$$i+1;' \
	  -e 'pop @parts; $$filter=join q{ }, map qq{"$$_"}, @parts;' \
	  -e 'pm_to_blib({@ARGV}, '\''$(INST_LIB)/auto'\'', $$filter, '\''$(PERM_DIR)'\'')' -- $(PM_FILTER) -- \
	  'lib/NicToolServer.pm' 'blib/lib/NicToolServer.pm' \
	  'lib/NicToolServer/Client.pm' 'blib/lib/NicToolServer/Client.pm' \
	  'lib/NicToolServer/Client/SOAP.pm' 'blib/lib/NicToolServer/Client/SOAP.pm' \
	  'lib/NicToolServer/Export.pm' 'blib/lib/NicToolServer/Export.pm' \
	  'lib/NicToolServer/Export/BIND.pm' 'blib/lib/NicToolServer/Export/BIND.pm' \
	  'lib/NicToolServer/Export/BIND/nsupdate.pm' 'blib/lib/NicToolServer/Export/BIND/nsupdate.pm' \
	  'lib/NicToolServer/Export/Base.pm' 'blib/lib/NicToolServer/Export/Base.pm' \
	  'lib/NicToolServer/Export/DynECT.pm' 'blib/lib/NicToolServer/Export/DynECT.pm' \
	  'lib/NicToolServer/Export/Knot.pm' 'blib/lib/NicToolServer/Export/Knot.pm' \
	  'lib/NicToolServer/Export/MaraDNS.pm' 'blib/lib/NicToolServer/Export/MaraDNS.pm' \
	  'lib/NicToolServer/Export/NSD.pm' 'blib/lib/NicToolServer/Export/NSD.pm' \
	  'lib/NicToolServer/Export/PowerDNS.pm' 'blib/lib/NicToolServer/Export/PowerDNS.pm' \
	  'lib/NicToolServer/Export/tinydns.pm' 'blib/lib/NicToolServer/Export/tinydns.pm' \
	  'lib/NicToolServer/Group.pm' 'blib/lib/NicToolServer/Group.pm' \
	  'lib/NicToolServer/Group/Sanity.pm' 'blib/lib/NicToolServer/Group/Sanity.pm' \
	  'lib/NicToolServer/Import/BIND.pm' 'blib/lib/NicToolServer/Import/BIND.pm' \
	  'lib/NicToolServer/Import/Base.pm' 'blib/lib/NicToolServer/Import/Base.pm' \
	  'lib/NicToolServer/Import/tinydns.pm' 'blib/lib/NicToolServer/Import/tinydns.pm' \
	  'lib/NicToolServer/Nameserver.pm' 'blib/lib/NicToolServer/Nameserver.pm' \
	  'lib/NicToolServer/Nameserver/Sanity.pm' 'blib/lib/NicToolServer/Nameserver/Sanity.pm' \
	  'lib/NicToolServer/Permission.pm' 'blib/lib/NicToolServer/Permission.pm' \
	  'lib/NicToolServer/Response.pm' 'blib/lib/NicToolServer/Response.pm' \
	  'lib/NicToolServer/SOAP.pm' 'blib/lib/NicToolServer/SOAP.pm' \
	  'lib/NicToolServer/Session.pm' 'blib/lib/NicToolServer/Session.pm' \
	  'lib/NicToolServer/User.pm' 'blib/lib/NicToolServer/User.pm' \
	  'lib/NicToolServer/User/Sanity.pm' 'blib/lib/NicToolServer/User/Sanity.pm' \
	  'lib/NicToolServer/Zone.pm' 'blib/lib/NicToolServer/Zone.pm' \
	  'lib/NicToolServer/Zone/Record.pm' 'blib/lib/NicToolServer/Zone/Record.pm' \
	  'lib/NicToolServer/Zone/Record/Sanity.pm' 'blib/lib/NicToolServer/Zone/Record/Sanity.pm' \
	  'lib/NicToolServer/Zone/Sanity.pm' 'blib/lib/NicToolServer/Zone/Sanity.pm' \
	  'lib/nictoolserver.conf' 'blib/lib/nictoolserver.conf' \
	  'lib/nictoolserver.conf.dist' 'blib/lib/nictoolserver.conf.dist' 
	$(NOECHO) $(TOUCH) pm_to_blib


# --- MakeMaker selfdocument section:

# here so even if top_targets is overridden, these will still be defined
# gmake will silently still work if any are .PHONY-ed but nmake won't

test_static ::
	$(NOECHO) $(NOOP)

test_dynamic ::
	$(NOECHO) $(NOOP)

static ::
	$(NOECHO) $(NOOP)

dynamic ::
	$(NOECHO) $(NOOP)

config ::
	$(NOECHO) $(NOOP)


# --- MakeMaker postamble section:


# End.
