---
abstract: 'NicTool API reference server'
author:
  - 'Matt Simerson <msimerson@cpan.org>'
  - 'Damon Edwards'
  - 'Abe Shelton'
  - 'Greg Schueler'
build_requires:
  Exporter: '0'
  Test: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'CPAN::Meta::Converter version 2.143240'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: NicToolServer
recommends:
  BIND::Conf_Parser: '1'
  JSON: '1'
  Mozilla::CA: '1'
  Net::DNS::ZoneFile: '1'
  Net::LDAP: '0.65'
  NicTool: '0'
requires:
  APR::Table: '0'
  Apache::DBI: '0'
  BIND::Conf_Parser: '0'
  CGI: '3'
  Crypt::KeyDerivation: '0'
  Crypt::Mac::HMAC: '0'
  CryptX: '0.021'
  Cwd: '0'
  DBD::mysql: '2.0416'
  DBI: '1.20'
  DBIx::Simple: '0'
  Data::Dumper: '0'
  English: '0'
  File::Copy: '0'
  File::Path: '0'
  IO::File: '0'
  JSON: '0'
  LWP::UserAgent: '0'
  MIME::Base32: '0'
  MIME::Base64: '0'
  Net::IP: '0'
  NicTool: '0'
  Params::Validate: '0.8'
  RPC::XML: '0'
  RPC::XML::Parser: '0'
  SOAP::Lite: '0.51'
  Scalar::Util: '0'
  Time::HiRes: '1.9'
  Time::Local: '0'
  Time::TAI64: '2'
  XML::Parser: '0'
  constant: '0'
  lib: '0'
  mod_perl: '0'
  parent: '0.2'
  strict: '0'
  vars: '0'
  warnings: '0'
version: '2.33'
